# Generated by Django 5.1.7 on 2025-03-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_carburants_dat_maj_alter_carburants_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stations',
            name='adresse',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='stations',
            name='code_departement',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='stations',
            name='code_postal',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='stations',
            name='code_region',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='stations',
            name='nom_departement',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='stations',
            name='nom_region',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='stations',
            name='ville',
            field=models.CharField(null=True),
        ),
    ]
