# Generated by Django 5.1.7 on 2025-03-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_alter_stations_adresse_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carburants",
            name="dat_maj",
            field=models.DateTimeField(null=True),
        ),
    ]
