# Generated by Django 5.1.7 on 2025-03-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0006_alter_carburants_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="LastReadingStationFuel",
            fields=[
                ("station_id", models.CharField(primary_key=True, serialize=False)),
                ("type_carburant", models.CharField()),
                ("prix", models.FloatField(null=True)),
                ("dat_maj", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "last_reading_by_station_and_fuel",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PriceCarburantsByStation",
            fields=[
                ("station_id", models.CharField(primary_key=True, serialize=False)),
                ("type_carburant", models.CharField()),
                ("prix", models.FloatField(null=True)),
            ],
            options={
                "db_table": "price_carburants_by_station",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RegionCheaperByFuel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom_region", models.CharField(null=True)),
                ("type_carburant", models.CharField()),
                ("prix", models.FloatField(null=True)),
                ("classement", models.IntegerField()),
            ],
            options={
                "db_table": "region_cheaper_by_fuel",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StationWithDiesel",
            fields=[
                ("station_id", models.CharField(primary_key=True, serialize=False)),
                ("adresse", models.CharField(max_length=255, null=True)),
                ("ville", models.CharField(max_length=255, null=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("code_postal", models.CharField(max_length=10, null=True)),
                ("automate_24_24", models.BooleanField()),
                ("prix", models.FloatField(null=True)),
                ("dat_maj", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "stations_with_diesel",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StationWithE10",
            fields=[
                ("station_id", models.CharField(primary_key=True, serialize=False)),
                ("adresse", models.CharField(max_length=255, null=True)),
                ("ville", models.CharField(max_length=255, null=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("code_postal", models.CharField(max_length=10, null=True)),
                ("automate_24_24", models.BooleanField()),
                ("prix", models.FloatField(null=True)),
                ("dat_maj", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "stations_with_e10",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StationWithE85",
            fields=[
                ("station_id", models.CharField(primary_key=True, serialize=False)),
                ("adresse", models.CharField(max_length=255, null=True)),
                ("ville", models.CharField(max_length=255, null=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("code_postal", models.CharField(max_length=10, null=True)),
                ("automate_24_24", models.BooleanField()),
                ("prix", models.FloatField(null=True)),
                ("dat_maj", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "stations_with_e85",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StationWithGPL",
            fields=[
                ("station_id", models.CharField(primary_key=True, serialize=False)),
                ("adresse", models.CharField(max_length=255, null=True)),
                ("ville", models.CharField(max_length=255, null=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("code_postal", models.CharField(max_length=10, null=True)),
                ("automate_24_24", models.BooleanField()),
                ("prix", models.FloatField(null=True)),
                ("dat_maj", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "stations_with_gpl",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StationWithSP95",
            fields=[
                ("station_id", models.CharField(primary_key=True, serialize=False)),
                ("adresse", models.CharField(max_length=255, null=True)),
                ("ville", models.CharField(max_length=255, null=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("code_postal", models.CharField(max_length=10, null=True)),
                ("automate_24_24", models.BooleanField()),
                ("prix", models.FloatField(null=True)),
                ("dat_maj", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "stations_with_sp95",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StationWithSP98",
            fields=[
                ("station_id", models.CharField(primary_key=True, serialize=False)),
                ("adresse", models.CharField(max_length=255, null=True)),
                ("ville", models.CharField(max_length=255, null=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("code_postal", models.CharField(max_length=10, null=True)),
                ("automate_24_24", models.BooleanField()),
                ("prix", models.FloatField(null=True)),
                ("dat_maj", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "stations_with_sp98",
                "managed": False,
            },
        ),
    ]
