# Generated by Django 5.1.7 on 2025-03-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0007_lastreadingstationfuel_pricecarburantsbystation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StationsCheaperByFuel",
            fields=[
                ("id", models.CharField(primary_key=True, serialize=False)),
                ("adresse", models.CharField(null=True)),
                ("code_postal", models.CharField(null=True)),
                ("ville", models.CharField(null=True)),
                ("type_carburant", models.CharField()),
                ("prix", models.FloatField(null=True)),
                ("classement", models.IntegerField()),
            ],
            options={
                "db_table": "stations_cheaper_by_fuel",
                "managed": False,
            },
        ),
    ]
