# Generated by Django 5.1.7 on 2025-04-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0008_stationscheaperbyfuel"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvolutionOfNationalFuelPrices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_maj", models.DateTimeField(null=True)),
                ("type_carburant", models.CharField()),
                ("prix_moyen", models.FloatField(null=True)),
            ],
            options={
                "db_table": "evolution_of_national_fuel_prices",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EvolutionOfStationFuelPrices",
            fields=[
                ("station_id", models.CharField(primary_key=True, serialize=False)),
                ("date_maj", models.DateTimeField(null=True)),
                ("type_carburant", models.CharField()),
                ("prix_moyen", models.FloatField(null=True)),
            ],
            options={
                "db_table": "evolution_of_station_fuel_prices",
                "managed": False,
            },
        ),
        migrations.AddField(
            model_name="stations",
            name="marque",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="stations",
            name="nom_station",
            field=models.CharField(null=True),
        ),
    ]
