# Generated by Django 5.1.7 on 2025-04-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0009_evolutionofnationalfuelprices"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvolutionOfStationFuelPrices",
            fields=[
                ("station_id", models.CharField(primary_key=True, serialize=False)),
                ("date_maj", models.DateTimeField(null=True)),
                ("type_carburant", models.CharField()),
                ("prix_moyen", models.FloatField(null=True)),
            ],
            options={
                "db_table": "evolution_of_station_fuel_prices",
                "managed": False,
            },
        ),
    ]
