# Generated by Django 5.1.7 on 2025-04-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0010_evolutionofstationfuelprices"),
    ]

    operations = [
        migrations.AddField(
            model_name="stations",
            name="marque",
            field=models.CharField(null=True),
        ),
    ]
