# Generated by Django 5.1.7 on 2025-09-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0011_stations_marque"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvgPricesE10",
            fields=[
                (
                    "avg_price",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "db_table": "avg_prices_e10",
                "managed": False,
            },
        ),
    ]
