# Generated by Django 5.1.7 on 2025-09-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0012_avgpricese10"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvgPricesDiesel",
            fields=[
                (
                    "avg_price",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "db_table": "avg_prices_diesel",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AvgPricesE85",
            fields=[
                (
                    "avg_price",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "db_table": "avg_prices_e85",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AvgPricesGPL",
            fields=[
                (
                    "avg_price",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "db_table": "avg_prices_e10",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AvgPricesSP95",
            fields=[
                (
                    "avg_price",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "db_table": "avg_prices_sp95",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AvgPricesSP98",
            fields=[
                (
                    "avg_price",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "db_table": "avg_prices_sp98",
                "managed": False,
            },
        ),
    ]
