# Generated by Django 5.1.7 on 2025-09-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0013_avgpricesdiesel_avgpricese85_avgpricesgpl_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvgPricesByFuel",
            fields=[
                ("type_carburant", models.CharField(primary_key=True, serialize=False)),
                ("avg_price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "db_table": "avg_prices_by_fuel",
                "managed": False,
            },
        ),
    ]
