on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: 🔑 Installer git-crypt
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "sudo apt-get install -y git-crypt"

      - name: pull
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull"

      - name: 🔓 Déverrouiller les fichiers avec git-crypt
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd ${{ secrets.WORK_DIR }} && \
            echo '${{ secrets.GIT_CRYPT_KEY }}' | base64 --decode > .env.key && \
            git-crypt unlock .env.key && \
            rm .env.key
          "

      - name: deploy
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}  "sudo docker-compose up -d --build carburants-web db-carburants db-airflow-carburants airflow-carburants nginx-proxy && exit"

      - name: cleanup
        run: rm -rf ~/.ssh